import {
  Network,
  LayoutGrid,
  FolderOpen,
  ShieldCheck,
  Plus,
  Search,
  ArrowRight,
  Download,
  Globe2,
  LockKeyhole,
  Pencil,
  LogOut,
  Link2,
  Check,
  Terminal,
  Minus,
  RotateCcw,
  Copy,
  FileJson2,
  Activity,
  Server,
  ExternalLink,
  type LucideIcon,
} from "lucide-react";
const icons: Record<string, LucideIcon> = {
  network: Network,
  grid: LayoutGrid,
  folder: FolderOpen,
  shield: ShieldCheck,
  plus: Plus,
  search: Search,
  arrow: ArrowRight,
  download: Download,
  globe: Globe2,
  lock: LockKeyhole,
  edit: Pencil,
  logout: LogOut,
  link: Link2,
  check: Check,
  terminal: Terminal,
  minus: Minus,
  reset: RotateCcw,
  copy: Copy,
  json: FileJson2,
  activity: Activity,
  server: Server,
  external: ExternalLink,
};
export function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const Component = icons[name] || Network;
  return <Component size={size} strokeWidth={1.5} aria-hidden="true" />;
}
